//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationASP1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // dodato
    
    public partial class order
    {
        public int IdOrder { get; set; }
        public string Name { get; set; }
        public Nullable<int> Amount { get; set; }
        public int IdDrink { get; set; }
    
        public virtual drink drink { get; set; }
    }
}
