//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationASP1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // dodato
    
    public partial class User
    {
        public int UserId { get; set; }

        public string FullName { get; set; }


        [Required(ErrorMessage = "Please Provide Username", AllowEmptyStrings = false)]   // dodato
        public string Username { get; set; }

        [Required(ErrorMessage = "Please provide password", AllowEmptyStrings = false)]  // dodato
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]  // dodato
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Password must be at least 3 char long.")] // dodato
        public string Password { get; set; }
    }
}
